### ISSUE TITLE
[FEATURE] 회원가입 성공시 회원 정보는 영구적으로 저장된다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#101]
Edited: @chhs2131  

## ✨ Describe
- JPA, mybatis 등을 이용한 데이터 저장 로직 구현 작업입니다.
- 사전작업: #193 
  - 프로젝트에 JPA 의존성이 추가되어있다.
  - MemberJpaRepository가 생성되어있다. 

<br/>

## ✅ Todo
- **회원 가입 영속성 로직 구현**
  - [x] 영속성 계층에서 활용되는 `MemberEntity` 구현
  - [x] Application 계층과 Persistence 계층간 데이터 교환을 위해 `MemberCoreRepository` 구현
  - [x] Domain <-> PersistenceEntity 변환을 위해 `Mapper`에 새로운 로직 추가 구현  
- **회원 가입 성공시 영구저장 로직 호출 테스트 작성**
  - [x] `MemberCoreRepositoryTest` 추가 
  - [x] `MapperTest`에 새로운 변환 로직 테스트 추가
- **RepositoryTest를 추가하여 해당 레이어 테스트에서 공통으로 활용할 수 있게 함**

<br/>

## 🙋🏻 More
- #51 와 중복된 기능이지만 명세를 명확히하기 위해서 작성했습니다.
