### ISSUE TITLE
[FEATURE] 거래 내역은 영구적으로 저장 관리된다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#112]
## ✨ Describe
- JPA를 이용한 데이터 저장 로직 구현 작업입니다

<br/>

## ✅ Todo
- **거래 내역 영속성 로직 구현**
  - [x] 영속성 계층에서 활용되는 `ReceiptEntity` 구현
  - [x] Application 계층과 Persistence 계층간 데이터 교환을 위해 `ReceiptRepository` 구현
      - [x] save, findById 구현
  - [x] Domain <-> PersistenceEntity 변환을 위해 `Mapper`에 새로운 로직 추가 구현  
- **거래 내역 영구저장 로직 호출 테스트 작성**
  - [x] `ReceiptCoreRepositoryTest` 추가 
  - [x] `MapperTest`에 새로운 변환 로직 테스트 추가
      - [x] 추상 클래스로 추출 후 테스트 추가 (도메인 -> 엔티티, 엔티티 -> 도메인)

<br/>
