### ISSUE TITLE
[FEATURE] 판매자는 경매 상품 목록에서 경매 식별자, 원가, 현재 판매가, 총 제고량, 현재 제고량, 시작시간, 종료시간을 확인할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#128]
### ✨ Describe
판매자 경매 상품 목록 조회시 노출되는 정보가 다를 수 있기 때문에 별도의 DTO를 생성해서 개발하는 것을  추천드립니다!

| 필드 | 설명 | 
| -- | -- |
| id | 경매 식별자 | 
| title | 경매 상품 display name | 
| originPrice | 원가 | 
| currentPrice | 현재가 | 
| totalStock | 총 제고량 | 
| currentStock | 현재 제고량 |
| startedAt | 경매 시작 시간 |
| endedAt | 경매 종료 시간 |

> 경매의 상태는 입력 받은 데이터를 기준으로 판단할 수 있기 때문에 포함하지 않습니다. 

### ✅ Todo
- [x] 경매 상품 목록 전용 DTO 생성
- [x] 경매 상품 목록 조회 서비스 메서드 생성
- [x] 경매 상품 목록 조회 repository 메서드 정의

**Comment by chhs2131** [comment]
구매자 입장에서 경매 목록을 조회하는 이슈는 아래를 참고하세요.
- #151
