### ISSUE TITLE
[FEATURE] 판매자는 자신의 경매 상품 목록을 조회할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#129]
### ✅ Todo
- [ ] [FEAT] 경매 내역 목록을 불러오는 API를 개발합니다
- [ ] [FEAT] 자신의 경매 내역만 볼 수 있게 조건을 추가합니다
- [ ] [TEST] 받아온 경매 내역이 판매자의 경매만 있는 지 확인합니다

| 속성 | 설명 | 
| -- | -- | 
| `auctionid` | 판매한 경매의 식별자입니다. | 
| `productName` | 상품의 이름입니다. | 
| `originPrice` | 원래 가격입니다. |
| `currentPrice` | 현재 가격입니다. |
| `originStock` | 원래 재고량입니다. |
| `currentStock` | 현재 재고량입니다. |

**Comment by minseok-oh** [comment]
#128 <- 여기서 구현되어 있어요...
