### ISSUE TITLE
[FEATURE] 구매자가 경매 목록 조회시 다음 정보를 포함한다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#151]
### ✨ Describe

| 속성 | 설명 | 필수 여부 |
|--|--|--|
| id | 경매 식별자 | `true` | 
| title |경매이름(display name) | `true` | 
| price |현재 가격 | `true` | 
| startedAt |시작 시간 |`true` | 
| finishedAt |종료 시간 |`true` | 

### ✅ Todo
- [x] 경매 목록 조회 dto 생성
- [x] 경매 목록 조회 repository interface(api) 정의
- [x] 경매 목록 조회 서비스 메서드 구현
