### ISSUE TITLE
[FEATURE] 사용자는 REST API를 통해서 로그인 요청을 할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#167]
Author: @HiiWee 

### ✨ Describe
- 사용자의 로그인 API 요청이 입력되면 실제 사용자를 조회 하여 매칭 및 로그인을 시켜줍니다.

### ✅ Todo
- [x] 사용자의 정보를 DB조회 후 로그인 가능한지 검증합니다.
- [x] 로그인이 완료됐다면 세션에 사용자의 정보를 저장합니다.
- [x] 사용자 로그인에 대한 API 문서를 생성합니다.
