### ISSUE TITLE
[FEATURE] 구매자는 거래 내역 목록에서 다음 정보를 확인할 수 있다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#175]
### ✨ Describe
구매자(일반 사용자)는 거래 내역에서 다음 정보를 확인할 수 있습니다.

| 속성 | 설명 | 
| -- | -- | 
| id | 거래 내역 식별자입니다. | 
| type | 거래 타입을 말합니다. 현재 거래 타입은 `BID`, `REFUND`가 존재합니다. | 
| auctionid | 구매한 경매의 식발자입니다. | 
| quantity | 구매 수량 | 
| price | 구매 가격 |
| productName | 거래 상품 이름 | 

### ✅ Todo
- [x] 구매자 거래 내역 목록 dto 생성
- [x] TransactionService 조회 메서드 생성
- [x] 조회 성공 테스트 케이스 작성

### 🙋🏻 More
- dto 네이밍 중 목록에서 사용하는 dto에서는 XXXSimpleInfo 이런식으로 네이밍을 진행함.

**Comment by yudonggeun** [comment]
- #221 에서 거래 상품 필드가 추가되었습니다.
