### ISSUE TITLE
[FEATURE] 로그인 한 사용자가 접근하면 사용자의 권한을 추출 및 저장할 수 있어야 합니다.

### ISSUE THREAD

**Issue by HiiWee** [woowa-techcamp-2024/Team7-ELEVEN#216]
### ✨ Describe
- `ArgumentResolver`를 통해 `@Login` 이 붙은 컨트롤러 파라미터를 리졸빙 하는 작업을 진행하려 합니다.

### ✅ Todo
- [x] 현재 사용자의 식별자를 담는 `AuthenticationContext` 객체를 생성한다.
  - [x]  `AuthenticationContext` 객체의 스코프는 `Request`로 요청때마다 새로 생성됩니다.
- [x] `AuthenticationInterceptor`는 사용자가 세션에 존재 할 경우 식별자를 `AuthenticaionContext`에 담는다.
- [x] `AuthenticationArgumentResolver`는 `@Login`이 붙은 인자를 만나면 리졸빙 작업을 한다.

### 🙋🏻 More
- 스프링에선 `Filter` -> `Interceptor` -> `ArgumentResolver` 순으로 진행하기 때문에 위 로직이 가능합니다.
