### ISSUE TITLE
[FEATURE] 로그인 한 사용자가 접근하면 세션에서 추출한 정보를 통해 사용자가 접근 가능한 API Endpoint 접근 여부를 허용하거나 거절합니다.

### ISSUE THREAD

**Issue by HiiWee** [woowa-techcamp-2024/Team7-ELEVEN#217]
### ✨ Describe
판매자 혹은 구매자가 접근 가능한 API endpoint를 구분하기 위해 Interceptor를 통해 Auth 검증을 진행 합니다.

### ✅ Todo
- [ ] 요청한 사용자의 세션에서 로그인 정보를 추출합니다.
- [ ] 요청한 핸들러가 사용자가 접근할 수 있는지 검사합니다.
  - [ ] 접근 엔드포인트가 사용자, 비로그인 사용자 모두 가능한 경우
  - [ ] 접근 엔드포인트가 구매자만 가능한 경우
  - [ ] 접근 엔드포인트가 판매자만 가능한 경우
