### ISSUE TITLE
[REFACTOR] 경매 생성 시 설정 가능한 시간의 폭을 늘려줍니다.

### ISSUE THREAD

**Issue by HiiWee** [woowa-techcamp-2024/Team7-ELEVEN#309]
### ✨ Describe

현재 경매 하락 기준 시간은 1, 5, 10분으로 고정되어 있습니다. 이에 대한 제약을 좀 더 자유롭게 주기 위해서 제약 시간을 자유롭게 넣을 수 있게 변경하려 합니다.

### ✅ Todo
- [x] 경매 지속 시간은 분 단위로 나누어 떨어지게 설정할 수 있고, 최대 1시간 까지 여야 합니다.(나노초 검증)
- [x] 경매 가격 하락 시간에 대한 제약을 없앱니다.
  - [x] `경매 지속 시간 / 경매 가격 하락 주기`가 나누어 떨어지는 시간이어야 합니다.

### 🙋🏻 More
추가 커밋: #315
