### ISSUE TITLE
[FEATURE] 사용자는 환불 시에 환불액을 주고 받는다

### ISSUE THREAD

**Issue by minseok-oh** [woowa-techcamp-2024/Team7-ELEVEN#60]
#### 검증 로직
    - 요청한 사용자가 구매자가 맞는가?
    - (판매자는 환불액보다 많은 포인트를 가지고 있는가? -> 구매자, 판매자 분리로 해결)

#### 구현 로직
    - 판매자는 환불액 (상품 금액 * 구매 수량)만큼 포인트를 차감한다
    - 구매자는 환불액 (상품 금액 * 구매 수량)만큼 포인트를 얻는다
    - 테스트 코드는 AuctionService의 자세한 구현이 나오기까지 사용할 스켈레톤을 구현한다

### ✅ Todo
- [ ] TEST CASE : 환불 성공시 판매자의 포인트가 환불액 만큼 차감되어야 한다.
- [ ] TEST CASE : 환불 성공시 구매자의 포인트가 환불액 만큼 증가되어야한다.
- [ ] TEST CASE : 환불 동시성 테스트 (Multi thread 동시성)

### 🙋🏻 More

- 추후 고민 사항
    - 동시성 이슈가 있는 FEATURE 입니다!
