### ISSUE TITLE
[FEATURE] 판매자는 자신의 경매만 수정이 가능하다.(제약조건 구현)

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#71]
### ✨ Describe
- #12 과 중복된 요구사항이 있을 수 있습니다. 
- 코드 상 구현되었다면 PR 없이 Comment에 간단하게 어느 클래스 어느 메서드에 구현이 되었는지 명시하고 close 해주세요!

### ✅ Todo
- [x] 자신의 경매가 아닌 경매를 수정하는 경우 실패 테스트 작성
- [x] #12 에서 기능이 구현되어있습니다.
- [x] #105 에서 검증 테스트를 작성하였습니다.

**Comment by yudonggeun** [comment]
- #12

**Comment by yudonggeun** [comment]
- #105 에서 검증 테스트를 작성하였습니다.
- #12 에서 기능이 구현되어있습니다.

**Comment by chhs2131** [comment]
AuctionService에 구현되어있음

```java
public void changeStock(SignInInfo signInInfo, UpdateAuctionStockCommand command) {
    if (!signInInfo.isType(Role.SELLER)) {
        throw new UnauthorizedException("판매자만 재고를 수정할 수 있습니다.", ErrorCode.A017);
    }
    Auction auction = findAuctionObject(command.auctionId());

    if (!auction.currentStatus(command.requestTime()).isWaiting()) {
        String message = String.format("시작 전인 경매의 재고만 수정할 수 있습니다. 시작시간=%s, 요청시간=%s", auction.getStartedAt(),
                command.requestTime());
        throw new BadRequestException(message, ErrorCode.A021);
    }
    if (!auction.isSeller(signInInfo.id())) {
        throw new UnauthorizedException("자신이 등록한 경매만 수정할 수 있습니다.", ErrorCode.A018);
    }

    auction.changeStock(command.changeRequestStock());

    auctionRepository.save(auction);
}
```
