### ISSUE TITLE
[FEATURE] 구매자가 구매시 구매한 수량만큼 경매의 재고가 차감된다.

### ISSUE THREAD

**Issue by yudonggeun** [woowa-techcamp-2024/Team7-ELEVEN#76]
Edit 2024/08/14/20:03 @HiiWee 

### ✨ Describe
- 입찰 로직으로, 구매자가 상품을 구매하면, 구매한 수량을 경매 물품 수에서 깎아주어야 합니다.

### ✅ Todo
- 검증 사항
  - [x] 남은 재고가 구매 요청 수량 이상인지
  - [x] 최소 1개 이상의 구매 요청 수량인지
  - [x] 최대 구매 가능 갯수보다 작거나 같은 구매 요청 수량인지
- 기능 사항
  - [x] 구매 요청이 오면 구매자가 넘겨준 price와 서버측의 price가 맞는지 검증한다.
    - [x] 가격 감소 검증은 시작 시간, 종료 시간 및 가격 하락 주기를 통해 계산하여 해당 시간에 요청한 가격과 일치하는지 검증합니다.
  - [x] 구매 요청 수량 만큼의 재고를 현재 재고에서 깎는다.

### 🙋🏻 More
- 동시성 이슈가 있을것으로 예상됩니다.
